version: "2"

linters:
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        type: goplugin
        path: build/plugins/linter.so
        description: "Checks logging messages"
        settings:
          check-lowercase: true
          sensitive-words: "password,token,api key,configtest"
